[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "Nptracer"
version = "0.0.1"

dependencies = [
 "numpy","pandas","pynbody"
]

[tool.setuptools]
packages = ["nptracer"]

[tool.setuptools.package-dir]
"Nptracer" = "nptracer"